services:
  mongodb:
    image: 'mongo:8.0.1'
    environment:
      - 'MONGO_INITDB_DATABASE=dosession_db'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'